### ISSUE TITLE
what does the parameter in test.py mean?

### ISSUE THREAD

**Issue by AOOOOOA** [ZJU-Robotics-Lab/Regular_voxelization#1]
Hi,
First of all, this is a wonderful project and has a good performance. But when I use it on my own dataset, I had some questions about the meaning of parameters. 

num_y = 120
num_x = 40
num_height = 20
max_height = 1  # max height
max_length = 1  # max_length in xy direction (same for x and y)

Could you please tell me the parameter meaning and what will happen if these values get bigger or smaller?

**Comment by MaverickPeter** [comment]
Hi, @AOOOOOA  
I apologize for the missing explanation in README.
The num_x/y/height is the voxel grid number in the x/y/z direction. More occupied information will be captured when this param gets bigger. Max_height/length means the max value of the input in z and x/y direction.

**Comment by AOOOOOA** [comment]
Sorry for the late response.

Thanks so much for your clear reply!
